// @generated by scripts/generate-provider-aggregates.mjs; do not edit by hand.
import type { ProviderAdapterModule } from './schemas/provider-adapter.js';
import { providerAdapter as anthropicProviderAdapter } from './providers/anthropic/adapter.js';
import { providerAdapter as ollamaProviderAdapter } from './providers/ollama/adapter.js';
import { providerAdapter as openaiProviderAdapter } from './providers/openai/adapter.js';

export * from './schemas/provider-adapter.js';
export { providerAdapter as anthropicAdapter, createAnthropicAdapter } from './providers/anthropic/adapter.js';
export { providerAdapter as ollamaAdapter, createOllamaAdapter, isToolCapableModel } from './providers/ollama/adapter.js';
export { providerAdapter as openaiAdapter, createChatCompletionsAdapter } from './providers/openai/adapter.js';

export const CERTIFIED_PROVIDER_ADAPTER_MODULES = [
  anthropicProviderAdapter,
  ollamaProviderAdapter,
  openaiProviderAdapter,
] as const satisfies readonly ProviderAdapterModule[];

export type CertifiedProviderAdapterKey =
  (typeof CERTIFIED_PROVIDER_ADAPTER_MODULES)[number]['adapterKey'];
