// @generated by scripts/generate-provider-aggregates.mjs; do not edit by hand.
import type { ProviderDefinition } from './schemas/provider-definition.js';
import { providerDefinition as anthropicProviderDefinition } from './providers/anthropic/definition.js';
import { providerDefinition as ollamaProviderDefinition } from './providers/ollama/definition.js';
import { providerDefinition as openaiProviderDefinition } from './providers/openai/definition.js';

export * from './schemas/provider-definition.js';

export const PROVIDER_DEFINITIONS = [
  anthropicProviderDefinition,
  ollamaProviderDefinition,
  openaiProviderDefinition,
] as const satisfies readonly ProviderDefinition[];

export type ProviderVendorKey = (typeof PROVIDER_DEFINITIONS)[number]['vendorKey'];
export type BootstrapProviderKey = ProviderVendorKey;

export function resolveProviderDefinition(vendorKey: ProviderVendorKey): ProviderDefinition {
  const definition = PROVIDER_DEFINITIONS.find(
    (candidate) => candidate.vendorKey === vendorKey,
  );
  if (!definition) {
    throw new Error(`Provider definition is missing for vendor key '${vendorKey}'`);
  }
  return definition;
}
